name: front-build-deploy

on:
  push:  
    paths:
      - front/**

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3

      - name: install dependencies
        working-directory: ./front
        run: npm install

      - name: build
        working-directory: ./front
        run: npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: ./front/build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-folder
          path: ./front/build
        
      - name: copy build to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ./*
          target: ${{ secrets.FRONT_DIR }}
